### ISSUE TITLE
Build fails on ROS 2 Iron, Jazzy + MoveIt 2

### ISSUE THREAD

**Issue by qboticslabs** [moveit/moveit_task_constructor#616] opened 2024-09-27 12:28 UTC
Hello

I am using ros2 branch on moveit 2 and ros 2 iron. Here is the build error I am getting

```
/home/robot/ws_moveit/src/moveit_task_constructor/core/include/moveit/task_constructor/solvers/cartesian_path.h:61:47: error: ‘CartesianPrecision’ in namespace ‘moveit::core’ does not name a type
   61 |         void setPrecision(const moveit::core::CartesianPrecision& precision) { setProperty("precision", precision); }
      |                                               ^~~~~~~~~~~~~~~~~~
/home/robot/ws_moveit/src/moveit_task_constructor/core/src/solvers/cartesian_path.cpp: In constructor ‘moveit::task_constructor::solvers::CartesianPath::CartesianPath()’:
/home/robot/ws_moveit/src/moveit_task_constructor/core/src/solvers/cartesian_path.cpp:63:33: error: ‘CartesianPrecision’ is not a member of ‘moveit::core’
   63 |         p.declare<moveit::core::CartesianPrecision>("precision", moveit::core::CartesianPrecision(),
      |                                 ^~~~~~~~~~~~~~~~~~
/home/robot/ws_moveit/src/moveit_task_constructor/core/src/solvers/cartesian_path.cpp:63:80: error: ‘CartesianPrecision’ is not a member of ‘moveit::core’
   63 |         p.declare<moveit::core::CartesianPrecision>("precision", moveit::core::CartesianPrecision(),
      |                                                                                ^~~~~~~~~~~~~~~~~~
/home/robot/ws_moveit/src/moveit_task_constructor/core/src/solvers/cartesian_path.cpp: In member function ‘virtual moveit::task_constructor::solvers::PlannerInterface::Result moveit::task_constructor::solvers::CartesianPath::plan(const PlanningSceneConstPtr&, const moveit::core::LinkModel&, const Isometry3d&, const Isometry3d&, const moveit::core::JointModelGroup*, double, robot_trajectory::RobotTrajectoryPtr&, const Constraints&)’:
/home/robot/ws_moveit/src/moveit_task_constructor/core/src/solvers/cartesian_path.cpp:124:37: error: ‘CartesianPrecision’ is not a member of ‘moveit::core’
  124 |             props.get<moveit::core::CartesianPrecision>("precision"), is_valid,
      |                                     ^~~~~~~~~~~~~~~~~~
/home/robot/ws_moveit/src/moveit_task_constructor/core/src/solvers/cartesian_path.cpp:124:56: error: no matching function for call to ‘moveit::task_constructor::PropertyMap::get<<expression error> >(const char [10]) const’
  124 |             props.get<moveit::core::CartesianPrecision>("precision"), is_valid,
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
In file included from /home/robot/ws_moveit/src/moveit_task_constructor/core/include/moveit/task_constructor/solvers/planner_interface.h:43,
                 from /home/robot/ws_moveit/src/moveit_task_constructor/core/include/moveit/task_constructor/solvers/cartesian_path.h:41,
                 from /home/robot/ws_moveit/src/moveit_task_constructor/core/src/solvers/cartesian_path.cpp:39:
/home/robot/ws_moveit/src/moveit_task_constructor/core/include/moveit/task_constructor/properties.h:324:18: note: candidate: ‘template<class T> const T& moveit::task_constructor::PropertyMap::get(const string&) const’
  324 |         const T& get(const std::string& name) const {
      |                  ^~~
/home/robot/ws_moveit/src/moveit_task_constructor/core/include/moveit/task_constructor/properties.h:324:18: note:   template argument deduction/substitution failed:
/home/robot/ws_moveit/src/moveit_task_constructor/core/src/solvers/cartesian_path.cpp:124:56: error: template argument 1 is invalid
  124 |             props.get<moveit::core::CartesianPrecision>("precision"), is_valid,
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
In file included from /home/robot/ws_moveit/src/moveit_task_constructor/core/include/moveit/task_constructor/solvers/planner_interface.h:43,
                 from /home/robot/ws_moveit/src/moveit_task_constructor/core/include/moveit/task_constructor/solvers/cartesian_path.h:41,
                 from /home/robot/ws_moveit/src/moveit_task_constructor/core/src/solvers/cartesian_path.cpp:39:
/home/robot/ws_moveit/src/moveit_task_constructor/core/include/moveit/task_constructor/properties.h:332:18: note: candidate: ‘template<class T> const T& moveit::task_constructor::PropertyMap::get(const string&, const T&) const’
  332 |         const T& get(const std::string& name, const T& fallback) const {
      |                  ^~~
/home/robot/ws_moveit/src/moveit_task_constructor/core/include/moveit/task_constructor/properties.h:332:18: note:   template argument deduction/substitution failed:
/home/robot/ws_moveit/src/moveit_task_constructor/core/src/solvers/cartesian_path.cpp:124:56: error: template argument 1 is invalid
  124 |             props.get<moveit::core::CartesianPrecision>("precision"), is_valid,
```

I would appreciate any help.

**Comment by rhaschke** [comment] 2024-09-27 13:27
This seems to be a duplicate of https://github.com/moveit/moveit_task_constructor/issues/455#issuecomment-2353627475
Try the (newly created) branch [`iron`](https://github.com/moveit/moveit_task_constructor/tree/iron).
Note that ROS Iron seems to have issues with Node cleanup, causing some unit tests to fail.

**Closed by rhaschke** 2024-09-27 13:27 UTC

**Comment by qboticslabs** [comment] 2024-09-27 17:43
@rhaschke Its building now. Thanks :)

**Comment by rhaschke** [comment] 2024-11-05 15:11
@ralphieraccoon: What problem do you observe exactly? The latest CI build ran successfully on Jazzy (except a failing test): https://github.com/moveit/moveit_task_constructor/actions/runs/11354223306/job/31580988546

**Comment by ralphieraccoon** [comment] 2024-11-05 15:23
> [@ralphieraccoon](https://github.com/ralphieraccoon): What problem do you observe exactly? The latest CI build ran successfully on Jazzy (except a failing test): https://github.com/moveit/moveit_task_constructor/actions/runs/11354223306/job/31580988546

```
--- stderr: moveit_task_constructor_core                                           
moveit_task_constructor_core: You did not request a specific build type: Choosing 'Release' for maximum performance
In file included from /home/ralphieraccoon/ros2_ws/src/moveit_task_constructor/core/src/solvers/cartesian_path.cpp:39:
/home/ralphieraccoon/ros2_ws/src/moveit_task_constructor/core/include/moveit/task_constructor/solvers/cartesian_path.h:61:47: error: ‘CartesianPrecision’ in namespace ‘moveit::core’ does not name a type
   61 |         void setPrecision(const moveit::core::CartesianPrecision& precision) { setProperty("precision", precision); }
      |                                               ^~~~~~~~~~~~~~~~~~
/home/ralphieraccoon/ros2_ws/src/moveit_task_constructor/core/src/solvers/cartesian_path.cpp: In constructor ‘moveit::task_constructor::solvers::CartesianPath::CartesianPath()’:
/home/ralphieraccoon/ros2_ws/src/moveit_task_constructor/core/src/solvers/cartesian_path.cpp:63:33: error: ‘CartesianPrecision’ is not a member of ‘moveit::core’
   63 |         p.declare<moveit::core::CartesianPrecision>("precision", moveit::core::CartesianPrecision(),
      |                                 ^~~~~~~~~~~~~~~~~~
/home/ralphieraccoon/ros2_ws/src/moveit_task_constructor/core/src/solvers/cartesian_path.cpp:63:80: error: ‘CartesianPrecision’ is not a member of ‘moveit::core’
   63 |         p.declare<moveit::core::CartesianPrecision>("precision", moveit::core::CartesianPrecision(),
      |                                                                                ^~~~~~~~~~~~~~~~~~
/home/ralphieraccoon/ros2_ws/src/moveit_task_constructor/core/src/solvers/cartesian_path.cpp: In member function ‘virtual moveit::task_constructor::solvers::PlannerInterface::Result moveit::task_constructor::solvers::CartesianPath::plan(const planning_scene::PlanningSceneConstPtr&, const moveit::core::LinkModel&, const Eigen::Isometry3d&, const Eigen::Isometry3d&, const moveit::core::JointModelGroup*, double, robot_trajectory::RobotTrajectoryPtr&, const moveit_msgs::msg::Constraints&)’:
/home/ralphieraccoon/ros2_ws/src/moveit_task_constructor/core/src/solvers/cartesian_path.cpp:124:37: error: ‘CartesianPrecision’ is not a member of ‘moveit::core’
  124 |             props.get<moveit::core::CartesianPrecision>("precision"), is_valid,
      |                                     ^~~~~~~~~~~~~~~~~~
/home/ralphieraccoon/ros2_ws/src/moveit_task_constructor/core/src/solvers/cartesian_path.cpp:124:56: error: no matching function for call to ‘moveit::task_constructor::PropertyMap::get<<expression error> >(const char [10]) const’
  124 |             props.get<moveit::core::CartesianPrecision>("precision"), is_valid,
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
In file included from /home/ralphieraccoon/ros2_ws/src/moveit_task_constructor/core/include/moveit/task_constructor/solvers/planner_interface.h:43,
                 from /home/ralphieraccoon/ros2_ws/src/moveit_task_constructor/core/include/moveit/task_constructor/solvers/cartesian_path.h:41:
/home/ralphieraccoon/ros2_ws/src/moveit_task_constructor/core/include/moveit/task_constructor/properties.h:324:18: note: candidate: ‘template<class T> const T& moveit::task_constructor::PropertyMap::get(const std::string&) const’
  324 |         const T& get(const std::string& name) const {
      |                  ^~~
/home/ralphieraccoon/ros2_ws/src/moveit_task_constructor/core/include/moveit/task_constructor/properties.h:324:18: note:   template argument deduction/substitution failed:
/home/ralphieraccoon/ros2_ws/src/moveit_task_constructor/core/src/solvers/cartesian_path.cpp:124:56: error: template argument 1 is invalid
  124 |             props.get<moveit::core::CartesianPrecision>("precision"), is_valid,
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
/home/ralphieraccoon/ros2_ws/src/moveit_task_constructor/core/include/moveit/task_constructor/properties.h:332:18: note: candidate: ‘template<class T> const T& moveit::task_constructor::PropertyMap::get(const std::string&, const T&) const’
  332 |         const T& get(const std::string& name, const T& fallback) const {
      |                  ^~~
/home/ralphieraccoon/ros2_ws/src/moveit_task_constructor/core/include/moveit/task_constructor/properties.h:332:18: note:   candidate expects 2 arguments, 1 provided
gmake[2]: *** [src/CMakeFiles/moveit_task_constructor_core.dir/build.make:230: src/CMakeFiles/moveit_task_constructor_core.dir/solvers/cartesian_path.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[1]: *** [CMakeFiles/Makefile2:364: src/CMakeFiles/moveit_task_constructor_core.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< moveit_task_constructor_core [1min 17s, exited with code 2]
```

**Comment by rhaschke** [comment] 2024-11-05 15:30
Ah, CI was building against jazzy-source, meaning a MoveIt2 source build. I guess, you are building against the binary packages of MoveIt? Could you try building MTC's iron branch? Does that already help?

**Comment by ralphieraccoon** [comment] 2024-11-05 15:35
> Ah, CI was building against jazzy-source, meaning a MoveIt2 source build. I guess, you are building against the binary packages of MoveIt? Could you try building MTC's iron branch? Does that already help?

```
--- stderr: moveit_task_constructor_core                                                                                             
moveit_task_constructor_core: You did not request a specific build type: Choosing 'Release' for maximum performance
/home/ralphieraccoon/ros2_ws/src/moveit_task_constructor/core/src/solvers/cartesian_path.cpp: In member function ‘virtual moveit::task_constructor::solvers::PlannerInterface::Result moveit::task_constructor::solvers::CartesianPath::plan(const planning_scene::PlanningSceneConstPtr&, const moveit::core::LinkModel&, const Eigen::Isometry3d&, const Eigen::Isometry3d&, const moveit::core::JointModelGroup*, double, robot_trajectory::RobotTrajectoryPtr&, const moveit_msgs::msg::Constraints&)’:
/home/ralphieraccoon/ros2_ws/src/moveit_task_constructor/core/src/solvers/cartesian_path.cpp:123:76: warning: ‘moveit::core::JumpThreshold::JumpThreshold(double)’ is deprecated: Use JumpThreshold::relative() instead. [-Wdeprecated-declarations]
  123 |             moveit::core::JumpThreshold(props.get<double>("jump_threshold")), is_valid,
      |                                                                            ^
In file included from /home/ralphieraccoon/ros2_ws/src/moveit_task_constructor/core/src/solvers/cartesian_path.cpp:44:
/opt/ros/jazzy/include/moveit_core/moveit/robot_state/cartesian_interpolator.h:74:60: note: declared here
   74 |   [[deprecated("Use JumpThreshold::relative() instead.")]] JumpThreshold(double relative_factor);
      |                                                            ^~~~~~~~~~~~~
/home/ralphieraccoon/ros2_ws/src/moveit_task_constructor/core/src/solvers/pipeline_planner.cpp: In constructor ‘moveit::task_constructor::solvers::PipelinePlanner::PipelinePlanner(const rclcpp::Node::SharedPtr&, const std::string&)’:
/home/ralphieraccoon/ros2_ws/src/moveit_task_constructor/core/src/solvers/pipeline_planner.cpp:128:104: error: ‘DISPLAY_PATH_TOPIC’ is not a member of ‘planning_pipeline::PlanningPipeline’
  128 |                         "publish generated solutions on topic " + planning_pipeline::PlanningPipeline::DISPLAY_PATH_TOPIC);
      |                                                                                                        ^~~~~~~~~~~~~~~~~~
/home/ralphieraccoon/ros2_ws/src/moveit_task_constructor/core/src/solvers/pipeline_planner.cpp:131:66: error: ‘MOTION_PLAN_REQUEST_TOPIC’ is not a member of ‘planning_pipeline::PlanningPipeline’
  131 |                             planning_pipeline::PlanningPipeline::MOTION_PLAN_REQUEST_TOPIC);
      |                                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/ralphieraccoon/ros2_ws/src/moveit_task_constructor/core/src/solvers/pipeline_planner.cpp: In member function ‘virtual void moveit::task_constructor::solvers::PipelinePlanner::init(const moveit::core::RobotModelConstPtr&)’:
/home/ralphieraccoon/ros2_ws/src/moveit_task_constructor/core/src/solvers/pipeline_planner.cpp:151:45: warning: ‘void planning_pipeline::PlanningPipeline::displayComputedMotionPlans(bool)’ is deprecated: Use generatePlan or ROS parameter API instead. [-Wdeprecated-declarations]
  151 |         planner_->displayComputedMotionPlans(properties().get<bool>("display_motion_plans"));
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/ralphieraccoon/ros2_ws/src/moveit_task_constructor/core/src/solvers/pipeline_planner.cpp:42:
/opt/ros/jazzy/include/moveit_ros_planning/moveit/planning_pipeline/planning_pipeline.h:134:73: note: declared here
  134 |   [[deprecated("Use generatePlan or ROS parameter API instead.")]] void displayComputedMotionPlans(bool /*flag*/){};
      |                                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/ralphieraccoon/ros2_ws/src/moveit_task_constructor/core/src/solvers/pipeline_planner.cpp:152:42: warning: ‘void planning_pipeline::PlanningPipeline::publishReceivedRequests(bool)’ is deprecated: Use generatePlan or ROS parameter API instead. [-Wdeprecated-declarations]
  152 |         planner_->publishReceivedRequests(properties().get<bool>("publish_planning_requests"));
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/ros/jazzy/include/moveit_ros_planning/moveit/planning_pipeline/planning_pipeline.h:135:73: note: declared here
  135 |   [[deprecated("Use generatePlan or ROS parameter API instead.")]] void publishReceivedRequests(bool /*flag*/){};
      |                                                                         ^~~~~~~~~~~~~~~~~~~~~~~
/home/ralphieraccoon/ros2_ws/src/moveit_task_constructor/core/src/solvers/pipeline_planner.cpp: In member function ‘moveit::task_constructor::solvers::PlannerInterface::Result moveit::task_constructor::solvers::PipelinePlanner::plan(const planning_scene::PlanningSceneConstPtr&, const moveit_msgs::msg::MotionPlanRequest&, robot_trajectory::RobotTrajectoryPtr&)’:
/home/ralphieraccoon/ros2_ws/src/moveit_task_constructor/core/src/solvers/pipeline_planner.cpp:214:67: error: ‘error_code_to_string’ is not a member of ‘moveit::core’; did you mean ‘errorCodeToString’?
  214 |         return { success, success ? std::string() : moveit::core::error_code_to_string(res.error_code.val) };
      |                                                                   ^~~~~~~~~~~~~~~~~~~~
      |                                                                   errorCodeToString
/home/ralphieraccoon/ros2_ws/src/moveit_task_constructor/core/src/solvers/pipeline_planner.cpp:214:108: error: could not convert ‘{success, <expression error>}’ from ‘<brace-enclosed initializer list>’ to ‘moveit::task_constructor::solvers::PlannerInterface::Result’
  214 |         return { success, success ? std::string() : moveit::core::error_code_to_string(res.error_code.val) };
      |                                                                                                            ^
      |                                                                                                            |
      |                                                                                                            <brace-enclosed initializer list>
In file included from /usr/include/c++/13/bits/stl_tempbuf.h:61,
                 from /usr/include/c++/13/memory:66,
                 from /opt/ros/jazzy/include/moveit_core/moveit/macros/declare_ptr.h:37,
                 from /opt/ros/jazzy/include/moveit_core/moveit/macros/class_forward.h:39,
                 from /home/ralphieraccoon/ros2_ws/src/moveit_task_constructor/core/include/moveit/task_constructor/solvers/planner_interface.h:41,
                 from /home/ralphieraccoon/ros2_ws/src/moveit_task_constructor/core/include/moveit/task_constructor/solvers/pipeline_planner.h:41,
                 from /home/ralphieraccoon/ros2_ws/src/moveit_task_constructor/core/src/solvers/pipeline_planner.cpp:39:
/usr/include/c++/13/bits/stl_construct.h: In instantiation of ‘void std::_Construct(_Tp*, _Args&& ...) [with _Tp = planning_pipeline::PlanningPipeline; _Args = {const shared_ptr<const moveit::core::RobotModel>&, const shared_ptr<rclcpp::Node>&, __cxx11::basic_string<char, char_traits<char>, allocator<char> >&, const char* const&, const __cxx11::basic_string<char, char_traits<char>, allocator<char> >&}]’:
/usr/include/c++/13/bits/alloc_traits.h:661:19:   required from ‘static void std::allocator_traits<std::allocator<void> >::construct(allocator_type&, _Up*, _Args&& ...) [with _Up = planning_pipeline::PlanningPipeline; _Args = {const std::shared_ptr<const moveit::core::RobotModel>&, const std::shared_ptr<rclcpp::Node>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, const char* const&, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&}; allocator_type = std::allocator<void>]’
/usr/include/c++/13/bits/shared_ptr_base.h:604:39:   required from ‘std::_Sp_counted_ptr_inplace<_Tp, _Alloc, _Lp>::_Sp_counted_ptr_inplace(_Alloc, _Args&& ...) [with _Args = {const std::shared_ptr<const moveit::core::RobotModel>&, const std::shared_ptr<rclcpp::Node>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, const char* const&, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&}; _Tp = planning_pipeline::PlanningPipeline; _Alloc = std::allocator<void>; __gnu_cxx::_Lock_policy _Lp = __gnu_cxx::_S_atomic]’
/usr/include/c++/13/bits/shared_ptr_base.h:971:16:   required from ‘std::__shared_count<_Lp>::__shared_count(_Tp*&, std::_Sp_alloc_shared_tag<_Alloc>, _Args&& ...) [with _Tp = planning_pipeline::PlanningPipeline; _Alloc = std::allocator<void>; _Args = {const std::shared_ptr<const moveit::core::RobotModel>&, const std::shared_ptr<rclcpp::Node>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, const char* const&, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&}; __gnu_cxx::_Lock_policy _Lp = __gnu_cxx::_S_atomic]’
/usr/include/c++/13/bits/shared_ptr_base.h:1712:14:   required from ‘std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::_Sp_alloc_shared_tag<_Tp>, _Args&& ...) [with _Alloc = std::allocator<void>; _Args = {const std::shared_ptr<const moveit::core::RobotModel>&, const std::shared_ptr<rclcpp::Node>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, const char* const&, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&}; _Tp = planning_pipeline::PlanningPipeline; __gnu_cxx::_Lock_policy _Lp = __gnu_cxx::_S_atomic]’
/usr/include/c++/13/bits/shared_ptr.h:464:59:   required from ‘std::shared_ptr<_Tp>::shared_ptr(std::_Sp_alloc_shared_tag<_Tp>, _Args&& ...) [with _Alloc = std::allocator<void>; _Args = {const std::shared_ptr<const moveit::core::RobotModel>&, const std::shared_ptr<rclcpp::Node>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, const char* const&, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&}; _Tp = planning_pipeline::PlanningPipeline]’
/usr/include/c++/13/bits/shared_ptr.h:1009:14:   required from ‘std::shared_ptr<typename std::enable_if<(! std::is_array< <template-parameter-1-1> >::value), _Tp>::type> std::make_shared(_Args&& ...) [with _Tp = planning_pipeline::PlanningPipeline; _Args = {const shared_ptr<const moveit::core::RobotModel>&, const shared_ptr<rclcpp::Node>&, __cxx11::basic_string<char, char_traits<char>, allocator<char> >&, const char* const&, const __cxx11::basic_string<char, char_traits<char>, allocator<char> >&}; typename enable_if<(! is_array< <template-parameter-1-1> >::value), _Tp>::type = planning_pipeline::PlanningPipeline]’
/home/ralphieraccoon/ros2_ws/src/moveit_task_constructor/core/src/solvers/pipeline_planner.cpp:106:66:   required from here
/usr/include/c++/13/bits/stl_construct.h:119:7: error: no matching function for call to ‘planning_pipeline::PlanningPipeline::PlanningPipeline(const std::shared_ptr<const moveit::core::RobotModel>&, const std::shared_ptr<rclcpp::Node>&, std::__cxx11::basic_string<char>&, const char* const&, const std::__cxx11::basic_string<char>&)’
  119 |       ::new((void*)__p) _Tp(std::forward<_Args>(__args)...);
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/ros/jazzy/include/moveit_ros_planning/moveit/planning_pipeline/planning_pipeline.h:126:3: note: candidate: ‘planning_pipeline::PlanningPipeline::PlanningPipeline(const moveit::core::RobotModelConstPtr&, const std::shared_ptr<rclcpp::Node>&, const std::string&, const std::vector<std::__cxx11::basic_string<char> >&, const std::vector<std::__cxx11::basic_string<char> >&, const std::vector<std::__cxx11::basic_string<char> >&)’
  126 |   PlanningPipeline(const moveit::core::RobotModelConstPtr& model, const std::shared_ptr<rclcpp::Node>& node,
      |   ^~~~~~~~~~~~~~~~
/opt/ros/jazzy/include/moveit_ros_planning/moveit/planning_pipeline/planning_pipeline.h:127:92: note:   no known conversion for argument 4 from ‘const char* const’ to ‘const std::vector<std::__cxx11::basic_string<char> >&’
  127 |                    const std::string& parameter_namespace, const std::vector<std::string>& planner_plugin_names,
      |                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
/opt/ros/jazzy/include/moveit_ros_planning/moveit/planning_pipeline/planning_pipeline.h:113:3: note: candidate: ‘planning_pipeline::PlanningPipeline::PlanningPipeline(const moveit::core::RobotModelConstPtr&, const std::shared_ptr<rclcpp::Node>&, const std::string&)’
  113 |   PlanningPipeline(const moveit::core::RobotModelConstPtr& model, const std::shared_ptr<rclcpp::Node>& node,
      |   ^~~~~~~~~~~~~~~~
/opt/ros/jazzy/include/moveit_ros_planning/moveit/planning_pipeline/planning_pipeline.h:113:3: note:   candidate expects 3 arguments, 5 provided
gmake[2]: *** [src/CMakeFiles/moveit_task_constructor_core.dir/build.make:258: src/CMakeFiles/moveit_task_constructor_core.dir/solvers/pipeline_planner.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:362: src/CMakeFiles/moveit_task_constructor_core.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< moveit_task_constructor_core [44.3s, exited with code 2]
```

Whole different bunch of errors I'm afraid.

**Comment by rhaschke** [comment] 2024-11-05 16:00
I pushed a new `jazzy` branch. Let's see what CI thinks of it: https://github.com/moveit/moveit_task_constructor/actions/runs/11687907179

**Comment by ralphieraccoon** [comment] 2024-11-05 16:33
`ros-jazzy-rmw-connextdds` failed to install. Seems like it is a valid `jazzy` package so worth running CI again just in case it's a one-off?
